### ISSUE TITLE
Replace copy-clipboard button with `ember-cli-clipboard`

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/builds#1]
Replace copy-clipboard button with https://github.com/jkusa/ember-cli-clipboard which uses https://clipboardjs.com/ internally (and avoids the flash dependency).

**Comment by locks** [comment]
Almost done.

**Comment by acorncom** [comment]
@locks Do you have this finished or should we label this as "Help Wanted" again to declare open season on it?

**Comment by locks** [comment]
@acorncom I think it's done but not pushed.
