### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by locks** [ember-learn/builds#47]
We are still showing bower instructions for installing Ember into your application, example: https://github.com/emberjs/website/issues/3008.
This instruction should be switched to use the `ember-source` npm package.

**Comment by AnupKumarGupta** [comment]
Hello, I want to work on this. Please let me know how to get started.

**Comment by locks** [comment]
@AnupKumarGupta thanks for the interest!

We need to update the file with the information on Ember releases to match Ember Data.
https://github.com/ember-learn/builds/blob/master/app/fixtures/ember/release.js#L16 This is the Ember line that needs to be changed.
https://github.com/ember-learn/builds/blob/master/app/fixtures/ember-data/release.js#L12 This is the Ember Data line that is using npm that you can take inspiration from.

**Comment by jkumar712** [comment]
@locks If it is still open, Can I open PR for this?

**Comment by jkumar712** [comment]
@locks Cant push my branch!

**Comment by rwwagner90** [comment]
@locks we can close this now right?

**Comment by locks** [comment]
Yup, thanks!
