### ISSUE TITLE
Change "Getting Started Guide" call to action

### ISSUE THREAD

**Issue by locks** [ember-learn/builds#59]
**Context:** 
At the moment it looks like the warning in the Guides about being in an older version of the Guides. Every time I visit the builds page my brain pattern matches hard. We should introduce a different style of call to action to this page.

**To-Do:** 
- [ ] Take the text out of the current call to action, and put it in a paragraph element with the class "lead". 
- [ ] Change the button into a regular link. 

**Screenshot (of current):**
![image](https://user-images.githubusercontent.com/4587451/34968531-624be482-fa2f-11e7-9eb5-fd1deb0f4756.png)

**Comment by SeanHealy33** [comment]
Decided to have a look at this :slightly_smiling_face: let me know what yous think!
