### ISSUE TITLE
Remove bower instructions and clarify install messaging for new users

### ISSUE THREAD

**Issue by jenweber** [ember-learn/builds#64]
WIP by @jenweber, @rwwagner90 with initial help from @rwjblue

**Comment by rwwagner90** [comment]
@jenweber we just merged the cleanup removing the bower stuff and replacing with npm. Is more needed for this?

**Comment by locks** [comment]
🚀

**Comment by jenweber** [comment]
@rwwagner90 thanks for bringing this to the finish line!!! Super awesome to have this in time for 3.0

**Comment by rwwagner90** [comment]
You're welcome @jenweber!
