### ISSUE TITLE
Resolve https mixed-content issues with builds.emberjs.com

### ISSUE THREAD

**Issue by acorncom** [ember-learn/builds#69]
I just put in a PR to attempt a fix for a mixed-content issue here: https://github.com/ember-learn/builds/pull/68

However, although that is required to remove the mixed-content errors in Chrome (isn't it?) our current build infrastructure (hosted on Amazon S3 I believe) doesn't apparently support https (I should have checked before putting in that PR).

How do we want to handle this? https://emberjs.com/ defaults to https (and I don't think we want to adjust that). @rwjblue are you able to update `builds.emberjs.com` so it serves content via https? Seems like that's our cleanest option ...

**Comment by rwjblue** [comment]
The fix is to use the alternate URL, sorry I didn't notice that before landing.

The URL we fetch from should be:

```
https://s3.amazonaws.com/builds.emberjs.com/canary.json
```

/cc @rwwagner90
